### ISSUE TITLE
Transformation on response did not take place when default JSON response transformation is defined

### ISSUE THREAD

**Issue by dsci** [Rohde-Schwarz/sparrow#11]
When a Sparrow configuration exists that says: 

```
config.default_json_response_key_transformation_strategy = :camelize
```

a HTTP header configuration:

```
'response-json-format':'underscore
```

will be ignored and the response will not be transformed. The keys are still camelcased.

**Comment by anmuel** [comment]
The spec says that it works. Now I'm not quite sure anymore. I guess we need to extend the testsuite to cover more cases.
